# Generated by Django 5.2.4 on 2025-07-14 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.TextField()),
                ('alternativa_a', models.CharField(max_length=300)),
                ('alternativa_b', models.CharField(max_length=300)),
                ('alternativa_c', models.CharField(max_length=300)),
                ('alternativa_d', models.CharField(max_length=300)),
                ('respuesta_correcta', models.CharField(max_length=1)),
                ('explicacion', models.TextField()),
            ],
        ),
    ]
