# Generated by Django 5.2.4 on 2025-07-18 01:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generador', '0002_tema_pregunta_tema'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repeticion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_revisada', models.DateTimeField(auto_now=True)),
                ('proxima_repeticion', models.DateTimeField(default=django.utils.timezone.now)),
                ('nivel_respuesta', models.IntegerField(choices=[(0, 'Incorrecta'), (1, 'Difícil'), (2, 'Bien'), (3, 'Fácil')], default=0)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generador.pregunta')),
            ],
        ),
    ]
