# Generated by Django 5.2.4 on 2025-07-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generador', '0004_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='repeticion',
            name='fecha_ultima_respuesta',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
