# Generated by Django 5.2.4 on 2025-07-25 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generador', '0005_repeticion_fecha_ultima_respuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='repeticion',
            name='difficulty',
            field=models.FloatField(default=0.3),
        ),
        migrations.AddField(
            model_name='repeticion',
            name='interval',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='repeticion',
            name='lapses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repeticion',
            name='stability',
            field=models.FloatField(default=1.0),
        ),
    ]
