# Generated by Django 5.2.4 on 2025-08-06 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generador', '0008_tema_padre_tema_usuario_alter_tema_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repeticion',
            name='modo',
            field=models.CharField(default='normal', max_length=20),
        ),
    ]
